17
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
Bienvenido a la instalacion de UTUTO XS GNU (http://www.ututo.org)             
-------------------------------------------------------------------------------
Creado por el equipo de trabajo del Proyecto UTUTO                             
-------------------------------------------------------------------------------
                                                                               
Con la colaboracion de SoLAr (www.solar.org.ar) y la Universidad Nacional      
de Salta (www.unsa.edu.ar)                                                     
                                                                               
                                                                               
                                                                               
                                                                               
Un especial agradecimiento a la FSF (www.fsf.org) por el reconocimiento.       
-------------------------------------------------------------------------------
Web Solar: http://www.solar.org.ar             Hipatia: http://www.hipatia.info
Web UTUTO: http://www.ututo.org                 GNU Project: http://www.gnu.org
                                                                               
-------------------------------------------------------------------------------
                                          [F1]  =  help / ayuda / hilfe / ajuda
-------------------------------------------------------------------------------
Presione [ENTER] / Press [ENTER]                                               
-------------------------------------------------------------------------------
