UTUTO XS install CD boot options - [F1 to display available kernels]

Please hit F1 to see the available kernels on this install cd.  

Please note that the -nofb counterparts to each kernel disable the framebuffer
and splash images. 

Additionally, the memtest86 boot option is available to test local RAM for 
errors. To use memtest86, just type 'memtest86'.

Possible command line options that can be used to tweak the boot process of 
this CD: all options that start with "do" have a "no" inverse, that does the 
opposite.  For example, "doscsi" enables SCSI support in the initial
ramdisk boot, while "noscsi" disables it.

To list the options, please press keys from F3 through F7.
   F3: Hardware (Page 1)
   F4: Hardware (Page 2)
   F5: Hardware (Page 3)
   F6: Volume Management
   F7: Misc.
